### PR TITLE
Add Language Switcher

### PR DESCRIPTION
**Pull request by crydotsnake**
I thought, it would look a bit prettier whit a language switcher! :D.

### CODE REVIEW

**Comment by crydotsnake** [comment]
Hmm, i dont have a idea.

**Comment by skerbis** [comment]
sorry for close

**Comment by skerbis** [comment]
we switch it automatically in help https://github.com/FriendsOfREDAXO/cke5/blob/8a6456c155afe0b765578eeba63017ff9e707057/pages/help.php#L12-L16

**Comment by crydotsnake** [comment]
Okay. It's okay @skerbis !

**Pull request closed without merging**
